import Link from 'next/link';
import type {Metadata} from 'next';
import {getSettings,getContent,getCategories,getProducts,getProduct} from '@/lib/store';
import Photo from '@/components/ui/Photo';
import ProductCard from '@/components/products/ProductCard';
import {localHref} from '@/lib/frontend';
import type {Product} from '@/types';
export async function generateMetadata():Promise<Metadata>{const s=await getSettings();return {title:s.seoTitle||s.businessName,description:s.seoDescription,alternates:{canonical:'/'},openGraph:{title:s.seoTitle||s.businessName,description:s.seoDescription}};}
export default async function Home(){const [s,c,categories]=await Promise.all([getSettings(),getContent(),getCategories()]);const cats=c.featuredCategories.length?c.featuredCategories.map(id=>categories.find(x=>x._id===id)).filter(x=>!!x):categories;const products=c.featuredProducts.length?(await Promise.all(c.featuredProducts.slice(0,10).map(id=>getProduct(id)))).filter((x):x is Product=>!!x):(await getProducts({limit:'5',featured:'1'})).items;return <><section className="hero"><div className="hero-copy"><h1 className="preline">{c.heroHeading}</h1><div className="ornament">—— ✥ ——</div><p>{c.heroSubtitle}</p><Link className="btn" href={localHref(c.heroCtaHref)}>{c.heroCtaLabel}</Link><div className="craft-values"><span>❈<br/>Artisan Inspired</span><span>✥<br/>Heritage Design</span><span>❦<br/>Timeless Style</span></div></div><Photo className="hero-photo" image={c.heroImage} priority alt={c.heroHeading} sizes="(max-width:700px) 100vw, 50vw"/></section>{cats.length>0&&<section className="container categories-section"><h2 className="section-title">✥ &nbsp; {c.categoriesHeading} &nbsp; ✥</h2><div className="category-grid">{cats.map(cat=><Link href={`/categories/${cat.slug}`} key={cat._id}><Photo className="category-photo" image={cat.image} alt={cat.name} sizes="(max-width:700px) 28vw, 15vw"/><span className="category-ornament">❈</span><h3>{cat.name}</h3></Link>)}</div></section>}{(c.aboutText||c.artisans.length>0)&&<section className="artisans"><div className="container artisan-grid"><div><h2>{c.aboutHeading}</h2><p>{c.aboutText}</p><Link className="btn outline" href="/about">Meet the artisans</Link></div>{c.artisans.map((a,i)=><article key={i}><Photo image={a.image} alt={a.name}/><h3>{a.name}</h3><small>{a.role}<br/>{a.location}</small></article>)}</div></section>}{c.banners.length>0&&<section className="container banner-grid">{c.banners.map((b,i)=><article className="banner" key={i}><div><h2>{b.title}</h2><p>{b.text}</p><Link className="btn rust" href={localHref(b.href)}>{b.ctaLabel}</Link></div><Photo image={b.image} alt={b.title}/></article>)}</section>}<section className="container product-section"><div className="section-head"><h2>{c.productsHeading}</h2><Link href="/shop">VIEW ALL</Link></div>{products.length?<div className="product-grid">{products.slice(0,5).map(p=><ProductCard key={p._id} product={p} currency={s.currency}/>)}</div>:<p className="empty">Our next collection is being prepared. Please check back soon.</p>}</section>{c.gallery.length>0&&<section className="container style-grid">{c.gallery.map((g,i)=><Link key={i} href={localHref(g.href)}><Photo image={g.image} alt={g.title}/><h3>{g.title}</h3></Link>)}</section>}</>;}
